name: flags
description: 250+ flags to use in you dream project, with just a single line of code.
version: 0.0.1
homepage: https://github.com/3kdeveloper/flags.git

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:

  assets:
    - assets/flags/
